#pragma config(Motor,  port1,           RearDriver,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port8,           RearPassanger, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FrontPassanger, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FrontDriver,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		//Forward and Backward movement "RIGHT joystick" VERTICAL
		motor[FrontDriver] = vexRT[Ch2];
		motor[RearDriver] = vexRT[Ch2];
		motor[FrontPassanger] = vexRT[Ch2];
		motor[RearPassanger] = vexRT[Ch2];

		//LEFT movement "RIGHT joystick" HORIZONTAL
		motor[FrontDriver] = vexRT[Ch3];
		motor[FrontPassanger] = -vexRT[Ch3];
		motor[RearDriver] = vexRT[Ch3];
		motor[RearPassanger] = -vexRT[Ch3];


}
