#pragma config(Sensor, in1,    BallLightSensor, sensorReflection)
#pragma config(Sensor, dgtl1,  LiftSonar,      sensorSONAR_raw)
#pragma config(Sensor, dgtl3,  LiftTouch,      sensorTouch)
#pragma config(Sensor, dgtl4,  LiftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           WinchLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Belt,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FlyLeft1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FlyLeft2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FlyLeft3,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           FlyRight1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FlyRight2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FlyRight3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           IntakeFunnel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          WinchRight,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void intake_set(int speed){
	motor(IntakeFunnel) = speed;
}

void belt_set(int speed){
	motor(Belt)  = speed;
}

void shooter_motor_set(int left, int right){
	motor(FlyRight1)  = right;
	motor(FlyRight2) = right;
	motor(FlyRight3)   = right;

	motor(FlyLeft1)  = left;
	motor(FlyLeft2) = left;
	motor(FlyLeft3)   = left;
}

int ball_light_sensor(){
	return SensorValue(BallLightSensor);
	}


task main()
{



}
