#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//initialize my variables//


while(true)
{
	motor[Right] = vexRT[Ch2];
	motor[Left] = vexRT[Ch3];

}
}
