#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  motor1sensor,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  motor2f,        sensorDigitalIn)
#pragma config(Sensor, dgtl3,  motor2r,        sensorDigitalIn)
#pragma config(Sensor, dgtl4,  encoder1,       sensorQuadEncoder)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motor10,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	int time = nSysTime;
	int enc = SensorValue[encoder1];

	int lastdisplay = 0;

	while(true){
		int newtime = nSysTime;
		int newenc = SensorValue[encoder1];
		int tickspersec = 0;
		if(newtime - time != 0)
			tickspersec = (newenc - enc) * 1000 / (newtime - time);
		time = newtime;
		enc = newenc;
		if(nSysTime - lastdisplay > 250){
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDNumber(0, 0, SensorValue[encoder1], 6);
			displayLCDNumber(1, 0, tickspersec, 6);
			lastdisplay = nSysTime;
		}

		motor[motor1]  = 127 * !SensorValue[motor1sensor];
		motor[motor10] = 127 * (SensorValue[motor2r] - SensorValue[motor2f]);

		delay(40);
	}
}
