#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl4,  encoder1,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encoder2,   sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  motor1sensor,        sensorDigitalIn)
#pragma config(Sensor, dgtl2,  motor2f,         sensorDigitalIn)
#pragma config(Sensor, dgtl3,  motor2r,       sensorDigitalIn)
#pragma config(Motor,  port1,           motor1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motor10,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		displayLCDNumber(0, 0, SensorValue[encoder1], 6);
		displayLCDNumber(1, 0, SensorValue[encoder2], 6);

		motor[motor1]  = 127 * !SensorValue[motor1sensor];
		motor[motor10] = 127 * (SensorValue[motor2f] - SensorValue[motor2r]);

		sleep(40);
	}
}
