#pragma config(Motor,  port1,           leftdrive,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightdrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (true) {

		motor[leftdrive] = vexRT[Ch2];
		motor[rightdrive] = vexRT[Ch2];
		motor[leftdrive] = vexRT[Ch1];
		motor[leftdrive] = vexRT[Ch1];

	}

}
