#pragma config(Sensor, in1,    BallSensor,     sensorReflection)
#pragma config(Sensor, dgtl1,  LiftSonar,      sensorNone)
#pragma config(Sensor, dgtl2,  Shooter,        sensorDigitalOut)
#pragma config(Sensor, dgtl3,  WinchRaised,     sensorTouch)
#pragma config(Sensor, dgtl4,  WinchEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           WinchLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Belt,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FlyLeft1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FlyLeft2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FlyLeft3,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           FlyRight3,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FlyRight2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FlyRight1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           IntakeFunnel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          WinchRight,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(45)
#pragma userControlDuration(75)

#include "largebot_control.h"

void pre_auton() {
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

}

task autonomous() {
		shooter_motor_set(SHOOTER_SPEED);
		belt_set(BELT_SPEED); //Belt on
		intake_set(INTAKE_SPEED); // Intake on
	while (true) {


		if( is_ball_ready()== 0 ) //If no ball in place
		{
			set_pneumatics(SHOOTER_IN); //Don't shoot
		}
		else //If ball in place
		{
			set_pneumatics(SHOOTER_OUT); //Shoot
		}

		if(smallbot_lift_ready()==1) //If Small Bot in place
		{
			winch_down_up(); //Extend winch to full length, then retract
		}
		// 6u -> shooter
		/*
		7u shooter start
		7d shooter stop
		7r decrese speed (by 1)
		7l increase speed (by 1)

		8u hold winch up
		8d hold winch dpwm

		5u toggle belts + intake on
		5d toggle belts + intake reverse
		*/
		;
	}
}

task usercontrol() {
		shooter_motor_set(vexRT[Ch3]);
		belt_set(BELT_SPEED); //Belt on
		intake_set(INTAKE_SPEED); // Intake on
	while (true) {

		if( is_ball_ready()== 0 ) //If no ball in place
		{
			set_pneumatics(SHOOTER_IN); //Don't shoot
		}
		else //If ball in place
		{
			set_pneumatics(SHOOTER_OUT); //Shoot
		}

		if(smallbot_lift_ready()==1) //If Small Bot in place
		{
			winch_down_up(); //Extend winch to full length, then retract
		}
		// 6u -> shooter
		/*
		7u shooter start
		7d shooter stop
		7r decrese speed (by 1)
		7l increase speed (by 1)

		8u hold winch up
		8d hold winch dpwm

		5u toggle belts + intake on
		5d toggle belts + intake reverse
		*/
		;
	}
}

#include "largebot_control.c"
