#pragma config(Motor,  port1,           RightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          LeftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/** Francisco's Learning Code:
	Move forward for 5 seconds
	Point turn right 3 seconds
	Move forward for 5 seconds
	swing turn left for 3 seconds
	Move backwards for 3 secs
		FIX MOTOR PORTS BEFORE TESTING
	**/

	motor[LeftMotor] = 127; //Move forward for 5 seconds
	motor[RightMotor] = 127;
	wait1Msec ( 5000 );

	motor[LeftMotor] = 0; //Pause for 1 sec
	motor[RightMotor] = 0;
	wait1Msec ( 1000 );

	motor[LeftMotor] = 127;//Point turn right 2 seconds
	motor[RightMotor] = -127;
	wait1Msec ( 2000 );

	motor[LeftMotor] = 63; //Move forward for 5 seconds
	motor[RightMotor] = 63;
	wait1Msec ( 5000 );

	motor[LeftMotor] = 63; //swing turn left for 3 seconds
	motor[RightMotor] = 127;
	wait1Msec ( 3000 );

	motor[LeftMotor] = -127; //Move backwards for 5 secs
	motor[RightMotor] = -127;
	wait1Msec ( 5000 );




}
