#pragma config(Sensor, dgtl1,  trigger,        sensorDigitalIn)
#pragma config(Sensor, dgtl2,  moveup,         sensorDigitalIn)
#pragma config(Sensor, dgtl3,  movedown,       sensorDigitalIn)
#pragma config(Motor,  port1,           shooter,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          arm,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		if(!SensorValue[trigger]){
			motor[shooter] = 127;
			motor[arm] = 0;
			sleep(5);
			motor[shooter] = 0;
		}
		motor[arm] = 80 * (!SensorValue[moveup] - !SensorValue[movedown]);
	}
}
