#pragma config(Motor,  port1,           leftdrive,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightdrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){

		motor[leftdrive] = vexRT[Ch2] + vexRT[Ch1];
		motor[rightdrive] = vexRT[Ch2] - vexRT[Ch1];
		motor[arm] = vexRT[Btn6U]*127 - vexRT[Btn6D]*127;
		motor[claw] = vexRT[Btn8U]*127 - vexRT[Btn8D]*127;

	}




}
