#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PowerExpander,  sensorAnalog)
#pragma config(Sensor, in6,    RightLine,      sensorLineFollower)
#pragma config(Sensor, in7,    MiddleLine,     sensorLineFollower)
#pragma config(Sensor, in8,    LeftLine,       sensorLineFollower)
#pragma config(Sensor, dgtl4,  EncoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  EncoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl12, Limit,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           RightPush,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightFront,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           RightMiddle,   tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port4,           RightRear,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           RightIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftFront,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           LeftMiddle,    tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port8,           LeftRear,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftIntake,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LeftPush,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// stores time since powered on; unsigned long nSysTime;

void waitNs(int seconds);

// cir_wheel = 10 + 3/8.0; // inches
// cir_wheelbase = 12 * 3.1415926;
// cir_wheel < cir_wheelbase / 4
// rot = enc_reading / 360.0;
// 3.633 wheel rev per robot 360 degree turns
// 1308 encoder reading for a 360 degree turn;
// 327 for 90 degrees
// THIS IS FOR TURNING ON THE CENTER OF ROTATION (aka both sides are doing rotating)

// main entry point
task main() {
    while (true) {
        motor_forward();
        waitNs(1);
        motor_stop();
        waitNs(1);
        motor_spin();
        waitNs(5);
    }
}


void motor_forward(){
    motor(rightFront)  = 100;
    motor(rightMiddle) = 100;
    motor(rightRear)   = 100;
    motor(leftFront)   = 100;
    motor(leftMiddle)  = 100;
    motor(leftRear)    = 100;
}

void motor_stop(){
    motor(rightFront)  = 0;
    motor(rightMiddle) = 0;
    motor(rightRear)   = 0;
    motor(leftFront)   = 0;
    motor(leftMiddle)  = 0;
    motor(leftRear)    = 0;
}

void motor_spin(){
    motor(rightFront)  =  100;
    motor(rightMiddle) =  100;
    motor(rightRear)   =  100;
    motor(leftFront)   = -100;
    motor(leftMiddle)  = -100;
    motor(leftRear)    = -100;
}

void waitNs(int seconds){
    delay(seconds * 1000);
}


void motor_set(int right, int left){
    motor(rightFront)  = right;
    motor(rightMiddle) = right;
    motor(rightRear)   = right;
    motor(leftFront)   = left;
    motor(leftMiddle)  = left;
    motor(leftRear)    = left;
}


rotate90(){
    int rightstart = SensorValue[EncoderRight];
    int leftstart = SensorValue[EncoderLeft];

    motor_set(10, -10);

    while ( (SensorValue[EncoderRight] - rightstart < 320) && (SensorValue[EncoderLeft] - leftstart > -320) ){ }

    motor_set(0, 0);
}
