#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PowerExpander,  sensorAnalog)
#pragma config(Sensor, in6,    RightLine,      sensorLineFollower)
#pragma config(Sensor, in7,    MiddleLine,     sensorLineFollower)
#pragma config(Sensor, in8,    LeftLine,       sensorLineFollower)
#pragma config(Sensor, dgtl4,  EncoderRight,   sensorQuadEncoder)
// encoder right alternate channel on dgtl5
#pragma config(Sensor, dgtl6,  EncoderLeft,    sensorQuadEncoder)
// encoder left alternate channel on dgtl7
// (left push) 10 and (right push) 11 are rear buttons
#pragma config(Sensor, dgtl12, Limit,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           RightPush,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightFront,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           RightMiddle,   tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port4,           RightRear,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           RightIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftFront,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           LeftMiddle,    tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port8,           LeftRear,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftIntake,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LeftPush,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Originall made by Mike L

task main()
{
while (1==1)
{
	motor(RightFront) = vexRT(Ch2);
	motor(RightMiddle) = vexRT(Ch2);
	motor(RightRear) = vexRT(Ch2);

	motor(LeftFront) = vexRT(Ch3);
	motor(LeftMiddle) = vexRT(Ch3);
	motor(LeftRear) = vexRT(Ch3);

	if (vexRT[Btn5U] == 1)
	{
		motor(RightPush) = 100;
		motor(LeftPush) = 100;
	}
	else if (vexRT[Btn5D] == 1)
	{
		motor(RightPush) = -100;
		motor(LeftPush) = -100;
	}
	else
	{
		motor(RightPush) = 0;
		motor(LeftPush) = 0;
	}


	if (vexRT[Btn6U] == 1)
	{
		motor(RightIntake) = 100;
		motor(LeftIntake) = 100;
	}
	else if (vexRT[Btn6D] == 1)
	{
		motor(RightIntake) = -100;
		motor(LeftIntake) = -100;
	}
	else
	{
		motor(RightIntake) = 0;
		motor(LeftIntake) = 0;
	}


}
}
