#pragma config(Sensor, in1,    lfONE,          sensorLineFollower)
#pragma config(Sensor, in2,    lfTWO,          sensorLineFollower)
#pragma config(Sensor, in3,    lfTHREE,        sensorLineFollower)
#pragma config(Motor,  port1,           Right,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Left,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		int input = SensorValue(lfONE);

	}
}
