#pragma config(Motor,  port1,           RearDriver,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port8,           RearPassanger, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FrontPassanger, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FrontDriver,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
			motor[FrontDriver] = vexRT[Ch3];
			motor[FrontPassanger] = vexRT[Ch2];
			motor[RearPassanger] = vexRT[Ch2];
			motor[RearDriver] = vexRT[Ch3];
	}
}
