#pragma config(Motor,  port1,           wheelR,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wheelL,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[wheelR] = vexRT[Ch2];
		motor[wheelL] = vexRT[Ch3];
		motor[arm] = vexRT[Btn8U]*50 - vexRT[Btn8D]*50;
		motor[claw] = vexRT[Btn5U]*125 - vexRT[Btn5D]*125;
	}
}
