#pragma config(Sensor, dgtl1,  Proximity,      sensorSONAR_inch)
#pragma config(Motor,  port1,           LeftM,         tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          RightM,        tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	/**
	Hey will this work?
	While the proximity sensor returns false keep moving forward
	**/


	while( SensorValue[dgtl1] == false )
	{
		motor[LeftM] = vexRT[Ch2];
		motor[RightM] = vexRT[Ch3];

	}


}
